#!/usr/bin/env bash
# This is a pre-commit hook that validates code formatting.
#
# Install this by running the script with an argument of "install",
# which installs a symlink to .git/hooks/precommit:
# $ ln -s ../../hooks/pre-commit .git/hooks/pre-commit

root="$(git rev-parse --show-toplevel 2>/dev/null)"

# Some sanity checking.
hash cargo || exit 1
[[ -n "$root" ]] || exit 1

# Installation.
if [[ "$1" == "install" ]]; then
    hook="$root"/.git/hooks/pre-commit
    if [[ ! -e "$hook" ]]; then
        ln -s ../../pre-commit "$hook"
        echo "Installed git pre-commit hook at $hook"
    else
        echo "Hook already installed"
    fi
    exit
fi

# Check formatting.
if [[ "$1" != "all" ]]; then
    msg="pre-commit stash @$(git rev-parse --short @) $RANDOM"
    trap 'git stash list -1 --format="format:%s" | grep -q "'"$msg"'" && git stash pop -q' EXIT
    git stash push -k -u -q -m "$msg"
fi
if ! errors=($(cargo fmt -- --check -l)); then
    echo "Formatting errors found."
    echo "Run \`cargo fmt\` to fix the following files:"
    for err in "${errors[@]}"; do
        echo "  $err"
    done
    exit 1
fi
if ! cargo clippy --tests; then
    exit 1
fi
if ! cargo test; then
    exit 1
fi
if [[ -n "$NSS_DIR" ]]; then
    if ! cargo clippy --tests --no-default-features --features nss; then
        exit 1
    fi
    if ! cargo test --no-default-features --features nss; then
        exit 1
    fi
fi
